# Generated by Django 3.0.7 on 2020-10-15 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Producto', models.CharField(max_length=100)),
                ('Descripcion', models.CharField(max_length=250)),
                ('Cantidad', models.IntegerField()),
                ('PrecioCliente', models.DecimalField(decimal_places=2, max_digits=20)),
                ('PrecioProvedor', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'verbose_name_plural': 'Inventario',
            },
        ),
        migrations.CreateModel(
            name='Probedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Probedor', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Probedores',
            },
        ),
        migrations.CreateModel(
            name='TransaccionesProbedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(auto_now_add=True)),
                ('Cantidad', models.IntegerField()),
                ('CostoTotal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Probedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezquinaDataApp.Probedor')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezquinaDataApp.Inventario')),
            ],
            options={
                'verbose_name_plural': 'Transacciones de Probedores',
            },
        ),
        migrations.CreateModel(
            name='TransaccionesClientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(auto_now_add=True)),
                ('Cantidad', models.IntegerField()),
                ('CostoTotal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezquinaDataApp.Inventario')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Transacciones de Clientes',
            },
        ),
    ]
