# Generated by Django 3.0.7 on 2020-10-16 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ezquinaDataApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccionesclientes',
            name='Producto',
        ),
        migrations.RemoveField(
            model_name='transaccionesclientes',
            name='Usuario',
        ),
        migrations.RemoveField(
            model_name='transaccionesprobedores',
            name='Probedor',
        ),
        migrations.RemoveField(
            model_name='transaccionesprobedores',
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
        migrations.DeleteModel(
            name='Probedor',
        ),
        migrations.DeleteModel(
            name='TransaccionesClientes',
        ),
        migrations.DeleteModel(
            name='TransaccionesProbedores',
        ),
    ]
